### ISSUE TITLE
requests文件安装完毕后，使用时出现报错

### ISSUE THREAD

**Issue by relic-oss** [honmashironeko/ProxyCat#19]
正在获取新的代理IP
Traceback (most recent call last):
  File "I:\NetAttackTools\Proxy\ProxyCat\ProxyCat-CN\ProxyCat-V1.9.py", line 460, in <module>
    server = AsyncProxyServer(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\NetAttackTools\Proxy\ProxyCat\ProxyCat-CN\ProxyCat-V1.9.py", line 49, in __init__
    self.proxies = self.load_proxies()
                   ^^^^^^^^^^^^^^^^^^^
  File "I:\NetAttackTools\Proxy\ProxyCat\ProxyCat-CN\ProxyCat-V1.9.py", line 63, in load_proxies
    new_ip = getip.newip()
             ^^^^^^^^^^^^^
  File "I:\NetAttackTools\Proxy\ProxyCat\ProxyCat-CN\getip.py", line 6, in newip
    response = requests.get(url)
               ^^^^^^^^^^^^^^^^^
  File "I:\Python\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Python\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Python\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\Python\Lib\site-packages\requests\sessions.py", line 486, in prepare_request
    p.prepare(
  File "I:\Python\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "I:\Python\Lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '': No scheme supplied. Perhaps you meant https://?

**Comment by honmashironeko** [comment]
用的是getip方式，但是你没有提供正确的API接口，请检查getip.py文件内容

**Comment by honmashironeko** [comment]
或者修改config.ini配置，将use_getip = True改为use_getip = False
